name: test

on: push 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
            python-version: 3.8
        run:|
            python3 -m pip install --upgrade pip
            pip install -r requiremente.txt

      - name: first step
        run: python3 workflow.py 2
