name: test

on: push 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - name: Install dependancies
        run: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: first step
        run: python3 browser_success.py
